[build]
  base = "/"
  command = "gatsby build"
  publish = "public"

[[redirects]]
  from = "https://rsapkf.netlify.app/*"
  to = "https://rsapkf.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/rss.xml"
  to = "/writing/rss.xml"
  status = 301
  force = true

[[redirects]]
  from = "/blog/the-rabbithole-series-part-1"
  to = "/blog/rabbithole-series-part-1"
  status = 301
  force = true
